name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-cpp-windows-2019:
    name: C++/MSVS (windows-2019)

    runs-on: windows-2019

    env:
      wxMSW_VER: 3.1.7
      WXWIN: c:\wx

    steps:
      - uses: actions/checkout@v3
      - name: Install wxWidgets
        run: |
          mkdir ${env:WXWIN} | Out-Null
          cd ${env:WXWIN}
        # curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxWidgets-${env:wxMSW_VER}-headers.7z
          curl -OL https://github.com/wxWidgets/wxWidgets/archive/refs/tags/vv${env:wxMSW_VER}.zip
        #  7z x wxWidgets-${env:wxMSW_VER}-headers.7z
        #  curl -OL https://github.com/wxWidgets/wxWidgets/releases/download/v${env:wxMSW_VER}/wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
        #  7z x wxMSW-${env:wxMSW_VER}_vc14x_x64_Dev.7z
          # cd /
          # mkdir build

      - name: Build
        # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        # run: cmake --build --config ${{env.BUILD_TYPE}}
        run: cmake . -G "MinGW Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RELEASE
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
        
   # - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #  run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}    
