name: Release project

on:
  push:
    tags:
    - '*'
      
jobs:      
  build:
    name: Building project
    uses: ./.github/workflows/cmake.yml
  upload:
    name: Uploading files
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifatcs
        uses: actions/download-artifact@v3
        with:
          name: Build output         
      - name: Upload application file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: channelcalc.exe
          asset_name: ChannelCalc_$tag.exe
          tag: ${{ github.ref }}
